# logCompressorClient.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 7
  selector:
    matchLabels:
      app: myapp 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
      - name: logdir
        hostPath:
          path: /var/log
      containers:
      - name: myapp
        image: alpine 
        volumeMounts:
         - name: logdir
           mountPath: /var/log     
        args: 
        - /bin/sh
        - -c
        - >
          while true; 
            do echo $(date) - Greetings from $HOSTNAME >> \
                 /var/log/$HOSTNAME.log ; 
            sleep 15; 
          done
