# serviceMultiplePorts.yaml
kind: Service
apiVersion: v1
metadata:
  name: python
spec:
  selector:
    run: python
  ports:
  - name: public
    protocol: TCP
    port: 80
    targetPort: 80
  - name: admin-console
    protocol: TCP
    port: 8080
    targetPort: 8080  
  type: LoadBalancer
  
 