# serviceSessionAffinity.yaml
kind: Service
apiVersion: v1
metadata:
  name: hello-app
spec:
  sessionAffinity: ClientIP
  selector:
    run: hello-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  
 